source .env
BUILD_FOLDER=build

rm -rf $BUILD_FOLDER
mkdir $BUILD_FOLDER

$PATH_TO_SJASMPLUS --fullpath --inc=. -DSNA_FILENAME=\"$BUILD_FOLDER/$PROJECT_NAME.sna\" -DBIN_FILENAME=\"$BUILD_FOLDER/$PROJECT_NAME.bin\" -DLABELSLIST_FILENAME=\"$BUILD_FOLDER/$PROJECT_NAME.labels\" src/main.asm

cp $BUILD_FOLDER/$PROJECT_NAME.sna $COPY_SNAPSHOT_TO
cp $BUILD_FOLDER/$PROJECT_NAME.labels $COPY_LABELSLIST_TO

$PATH_TO_AUTORUN